 create database clinic;

create table patients (id int primary key generated always as identity,
  name varchar(100), 
  date_of_birth date);

create table medical_histories (id int primary key generated always as identity, 
admitted_at timestamp, 
patient_id int, 
constraint fk_patient_id 
    foreign key (patient_id) 
    references patients(id), 
status varchar(100));

CREATE TABLE treatments (
  id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type            CHAR(100)    NOT NULL,
  name            CHAR(100)    NOT NULL
);

CREATE TABLE invoices (
  id                    INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  total_amount          DECIMAL    NOT NULL,
  generated_at          TIMESTAMP    NOT NULL,
  payed_at              TIMESTAMP    NOT NULL,
  medical_history_id    int    NOT NULL,
  FOREIGN KEY (medical_history_id) REFERENCES medical_histories (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE invoice_items (
  id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  unit_price      DECIMAL    NOT NULL,
  quantity        int    NOT NULL,
  total_price     DECIMAL    NOT NULL,
  invoice_id      int    NOT NULL,
  treatment_id    int    NOT NULL,
  FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (treatment_id) REFERENCES treatments (id) ON DELETE RESTRICT ON UPDATE CASCADE,
);
