CREATE DATABASE clinic;

CREATE TABLE patients (
  id              INT  PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name            CHAR(100) NOT NULL, 
  date_of_birth   DATE NOT NULL
);

CREATE TABLE medical_histories (
  id              INT  PRIMARY KET GENERATED ALWAYS AS IDENTITY,
  admitted_at     TIMESTAMP, 
  patient_id      INT, 
  FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE RESTRICT ON UPDATE CASCADE, 
  status          CHAR(100) NOT NULL);

CREATE TABLE treatments (
  id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type            CHAR(100)    NOT NULL,
  name            CHAR(100)    NOT NULL
);

CREATE TABLE invoices (
  id                    INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  total_amount          DECIMAL    NOT NULL,
  generated_at          TIMESTAMP    NOT NULL,
  payed_at              TIMESTAMP    NOT NULL,
  medical_history_id    int    NOT NULL,
  FOREIGN KEY (medical_history_id) REFERENCES medical_histories (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE invoice_items (
  id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  unit_price      DECIMAL    NOT NULL,
  quantity        int    NOT NULL,
  total_price     DECIMAL    NOT NULL,
  invoice_id      int    NOT NULL,
  treatment_id    int    NOT NULL,
  FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (treatment_id) REFERENCES treatments (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
